global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'users-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: users-service

  - job_name: 'products-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3001']
        labels:
          service: products-service

  - job_name: 'checkout-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3003']
        labels:
          service: checkout-service

  - job_name: 'payments-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3004']
        labels:
          service: payments-service

  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3005']
        labels:
          service: api-gateway
