packages:
  - 'libs/*'
  - 'apps/*'
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': false
  '@scarf/scarf': false
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  sharp: true
  unrs-resolver: false

# catalog:
#   '@myorg/events': 'libs/events'
#   '@myorg/core': 'libs/core'

injectWorkspacePackages: true
