packages:
  - 'libs/*'
  - 'apps/*'
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': false
  sharp: true
  unrs-resolver: false

catalog:
  '@myorg/events': 'libs/events'

injectWorkspacePackages: true
