version: '3.0'

services:
  logger-db:
    image: postgres
    container_name: logger-db
    environment:
      POSTGRES_DB: logger_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5305:5432"
    volumes:
      - logger_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - logger-network

volumes:
  logger_db_data:

networks:
  logger-network:
    driver: bridge