version: '3.0'

services:
  payment-db:
    image: postgres
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5305:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - payment-network

volumes:
  payment_db_data:

networks:
  payment-network:
    driver: bridge